import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "App title",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="p-4 m-2 bg-zinc-500 rounded-2xl text-white">
          <div className="p-2 text-2xl"> 
              <Link href={"/user/signup"}>signup</Link>
          </div>
          <div className="p-2 text-2xl" >
              <Link href={"/user/signin"}>signin</Link>
          </div>
        </div>
        
        {children}
      </body>
    </html>
  );
}
